
name: ğŸš€ Deploy App

on:
  push:
    branches: [main]
    paths:
      - App/**/*
  workflow_dispatch:
    branches: [main]
    
jobs:

  Build-Deploy-App:
    name: ğŸ‰ Deploy App
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: ./App
    env:
      npm_config_user: root
    steps:

      - name: ğŸšš Get latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
          persist-credentials: false

      - name: âš™ï¸ Install dependancies
        run: npm ci

      - name: ğŸ› ï¸ Build React app
        run: npm run build

      - name: ğŸ“‚ Sync files
        uses: Stiwoz/git-sftp-action@master
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
          local_path: './App/build/*'
          remote_path: ${{ secrets.PATH }}/public
          port: 22
          args: '-o ConnectTimeout=30'
