
name: ðŸš€ Deploy on push

on:
  push:
    branches: [main]
  workflow_dispatch:


jobs:

  Build-Deploy-App:
    name: ðŸŽ‰ Deploy App
    runs-on: ubuntu-latest
    continue-on-error: false
    defaults:
      run:
        working-directory: ./App
    steps:

      - name: ðŸšš Get latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
          persist-credentials: false

      - name: ðŸ“š Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.0.0
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependancies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: ðŸ“‚ Sync files
        uses: Stiwoz/git-sftp-action@master
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
          local_path: './App/build/*'
          remote_path: ${{ secrets.PATH }}/public
          port: 22
          args: '-o ConnectTimeout=30'

  Deploy-Api:
    name: ðŸŽ‰ Deploy Api
    runs-on: ubuntu-latest
    continue-on-error: false
    defaults:
      run:
        working-directory: ./Api
    steps:

      - name: ðŸšš Get latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
          persist-credentials: false

      - name: ðŸ“‚ Sync files
        uses: Stiwoz/git-sftp-action@master
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
          local_path: './Api/*'
          remote_path: ${{ secrets.PATH }}
          port: 22
          args: '-o ConnectTimeout=30'
      
      - name: Install Python dependancies
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: cd ${{ secrets.PATH }} && pip install -r requirements.txt
      
      - name: Sync League & Std data
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: cd ${{ secrets.PATH }} && python priceValueLP.py && python priceValueLP.py standard